create database BMS_DB1;
use BMS_DB1;

-- CUSTOMER_PERSONAL_INFO

create table CUSTOMER_PERSONAL_INFO
(
CUSTOMER_ID VARCHAR(5),
CUSTOMER_NAME VARCHAR(50),
DATE_OF_BIRTH DATE,
GUARDIAN_NAME VARCHAR(50),
CONTACT_NO BIGINT(10),
MAIL_ID VARCHAR(20),
GENDER CHAR(1),
MARITAL_STATUS VARCHAR(20),
IDENTIFICATION_DOC_TYPE VARCHAR(20),
ID_DOC_NO VARCHAR(20),
CITIZENSHIP VARCHAR(10),
CONSTRAINT CUST_PERS_INFO_PK PRIMARY KEY(CUSTOMER_ID)
);
show tables;

-- CUSTOMER REFERENCE_INFO

 create table CUSTOMER_REFERENCE_INFO
 (
 CUSTOMER_ID VARCHAR(5),
 REFERENCE_ACC_NAME VARCHAR(20),
 REFEREENCE_ACC_NO BIGINT(16),
 REFERENCE_ACC_ADDRESS VARCHAR(50),
 RELATION VARCHAR(25),
 CONSTRAINT CUST_REF_INFO_PK PRIMARY KEY(CUSTOMER_ID),
 CONSTRAINT CUST_REF_INFO_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
 );
 show tables;

CREATE TABLE BANK_INFO
(
IFSC_CODE VARCHAR(15),
BANK_NAME VARCHAR(25),
BRANCH_NAME VARCHAR(25),
CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
);

-- ACCOUNT_INFO
CREATE TABLE ACCOUNT_INFO
(
ACCOUNT_NO BIGINT(16),
CUSTOMER_ID VARCHAR(5),
ACCOUNT_TYPE VARCHAR(50),
REGISTRATION_DATE DATE,
ACTIVATION_DATE DATE,
IFSC_CODE VARCHAR(16),
INTEREST DECIMAL(7,2),
INITIAL_DEPOSIT BIGINT(10),
CONSTRAINT ACC_REF_INFO_PK PRIMARY KEY(ACCOUNT_NO),
CONSTRAINT ACC_INFO_PERS_FK  FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_REFERENCE_INFO(CUSTOMER_ID),
CONSTRAINT ACC_INFO_BANK_FK FOREIGN KEY(IFSC_CODE) REFERENCES BANK_INFO(IFSC_CODE)
);
show tables;

-- BANK INFO 

INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES("HDVL0012","HDFC","SHAMLI");
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES("SBITN0123","SBI","THANABHWAN");
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES("ICITN0232","ICICI","SHAMLI");
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES("BOBOT123","BANK OF BADOTHA","SHAMLI");
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME)VALUES("AXIS01D23","AXIS","THANABHAWAN");

SELECT * FROM BANK_INFO;

-- CUSTOMER_PERSONAL_INFO

INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARITAL_STATUS)VALUES("C-001","RAMESH","12-09-1985","KIRAN","NO.14 MG ROAD,SHAMLI",7846633379,"HDHDYGD@GMAIL.COM","M","MARRIED");
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARITAL_STATUS)VALUES("C-002","ARIFA",11-06-1975,"SHAHJAD","NO.15 SAHRUNPUR ROAD,SHAMLI",9846633769,"SHBHBD@GMAIL.COM","F","UNMARRIED");
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARITAL_STATUS)VALUES("C-003","ANUJ",15-01-1990,"KIRAN","NO.08 MUZFF ROAD,SHAMLI",8646633325,"JBSHOSK@GMAIL.COM","M","MARRIED");
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARITAL_STATUS)VALUES("C-004","RAMESH",12-09-1985,"KIRAN","NO.14 MG ROAD,SHAMLI",7766643379,"KDJIOD@GMAIL.COM","M","MARRIED");
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARITAL_STATUS)VALUES("C-005","KIRAN",23-10-1979,"SHIVAM","NO.14 MG ROAD,SHAMLI",8477388284,"JSHFJ@GMAIL.COM","M","UNMARRIED");

SELECT * FROM CUSTOMER_PERSONAL_INFO;

-- CUSTOMER_REFERENCE_INFO

INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS,RELATION)VALUES(C001,'JOHN SMITH',1234567890,'123 MAIN ST,ANTOWN,INDIA','INDIA');
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS,RELATION)VALUES(C002,'JANE DOE',4564567230,'465 ELMT ST,OTHERTOWN,USA','USA');
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS,RELATION)VALUES(C003,'RAMESH',6784567890,'453 MAIN ST,ANTOWN,INDIA','INDIA');
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID,REFERENCE_ACC_NAME,REFERENCE_ACC_NO,REFERENCE_ACC_ADDRESS,RELATION)VALUES(C004,'ANUJ',9734567340,'657 PINE ST,THISTWON,CANADA','CANADA');

SELECT * FROM CUSTOMER_REFERENCE_INFO;
